name: Continuous Integration
on: [push]

jobs:
  phpunit:
    name: Unit Tests
    runs-on: ubuntu-latest
    container:
      image: davidalger/php:8.0
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: composer2 install

      - name: Test
        run: vendor/bin/phpunit tests --testdox

  phpstan:
    name: Static Analysis Check
    runs-on: ubuntu-latest
    container:
      image: davidalger/php:8.0
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: composer2 install

      - name: Run PHPStan
        run: vendor/bin/phpstan analyse src --level max

  infection:
    name: Infection Check
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0
          coverage: xdebug
          tools: composer:v2

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: composer install

      - name: Check for Mutants
        run: vendor/bin/infection --threads=$(nproc)
